[package]
name = "tictactoe"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"